// Generated by scripts/generate-indexing.mjs. Edit src/indexing.ts and regenerate.
import { indexer } from 'envio';
import { chainKey, normalizedEvent } from './eventLog.js';

indexer.contractRegister({"contract":"PonsV2Factory","event":"TokenLaunched"}, async ({ event, context }) => {
    context.chain.PonsV2Curve.add(event.params.curve);
    context.chain.PonsLaunchToken.add(event.params.token);
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchConfigUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchConfigUpdated", "LaunchConfigUpdated(uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchFeeUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchFeeUpdated", "LaunchFeeUpdated(uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchEnabledUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchEnabledUpdated", "LaunchEnabledUpdated(bool)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"MaxCreatorTaxUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "MaxCreatorTaxUpdated", "MaxCreatorTaxUpdated(uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"SnipeTaxStartBpsUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "SnipeTaxStartBpsUpdated", "SnipeTaxStartBpsUpdated(uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"SnipeTaxSecondsUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "SnipeTaxSecondsUpdated", "SnipeTaxSecondsUpdated(uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchDeployerSet"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchDeployerSet", "LaunchDeployerSet(address)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchForwarderSet"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchForwarderSet", "LaunchForwarderSet(address)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"PairTokenApprovalUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "PairTokenApprovalUpdated", "PairTokenApprovalUpdated(address,bool)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"PairTokenEconomicsUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "PairTokenEconomicsUpdated", "PairTokenEconomicsUpdated(address,uint256,uint256,uint8)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"TokenLaunched"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "TokenLaunched", "TokenLaunched(address,address,address,address,uint256,uint256)"));
    {
      const id = chainKey(event.chainId, event.params.token.toLowerCase());
      const existing = await context.PonsLaunch.get(id);
      context.PonsLaunch.set({
        id,
        token: event.params.token.toLowerCase(),
        curve: event.params.curve.toLowerCase(),
        deployer: event.params.deployer.toLowerCase(),
        pairToken: event.params.pairToken.toLowerCase(),
        launchConfigId: event.params.launchConfigId,
        graduationThreshold: event.params.graduationThreshold,
        canonicalSupply: existing?.canonicalSupply,
        createdBlock: BigInt(event.block.number),
        supplyMintBlock: existing?.supplyMintBlock,
      });
    }
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchSwept"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchSwept", "LaunchSwept(address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"CreatorFeeRecipientUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "CreatorFeeRecipientUpdated", "CreatorFeeRecipientUpdated(address,address,address)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"BuybackEnabledUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "BuybackEnabledUpdated", "BuybackEnabledUpdated(address,bool,address)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"PoolGraduated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "PoolGraduated", "PoolGraduated(address,uint256,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Factory","event":"LaunchGraduationRescued"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Factory", "LaunchGraduationRescued", "LaunchGraduationRescued(address,address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"CurveBuy"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "CurveBuy", "CurveBuy(address,address,uint256,uint256,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"CurveBuyRefunded"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "CurveBuyRefunded", "CurveBuyRefunded(address,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"CurveSell"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "CurveSell", "CurveSell(address,address,uint256,uint256,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"FeesSwept"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "FeesSwept", "FeesSwept(uint256,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"BuybackLocked"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "BuybackLocked", "BuybackLocked(uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2Curve","event":"CurveCompleted"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Curve", "CurveCompleted", "CurveCompleted(address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2MemeHook","event":"PoolRegistered"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2MemeHook", "PoolRegistered", "PoolRegistered(bytes32,address,address,address)"));
    {
      const id = chainKey(event.chainId, event.params.poolId.toLowerCase());
      const existing = await context.PonsPool.get(id);
      context.PonsPool.set({
        id,
        token: event.params.memecoin.toLowerCase(),
        quoteToken: event.params.quoteToken.toLowerCase(),
        creator: event.params.creator.toLowerCase(),
        registeredBlock: BigInt(event.block.number),
      });
    }
});

indexer.onEvent({"contract":"PonsV2MemeHook","event":"ProtocolFeeRecipientUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2MemeHook", "ProtocolFeeRecipientUpdated", "ProtocolFeeRecipientUpdated(address)"));
});

indexer.onEvent({"contract":"PonsV2MemeHook","event":"HookFeeCollected"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2MemeHook", "HookFeeCollected", "HookFeeCollected(bytes32,address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2MemeHook","event":"PoolFeesSwept"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2MemeHook", "PoolFeesSwept", "PoolFeesSwept(bytes32,uint256,uint256,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2MemeHook","event":"PoolFeesRescued"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2MemeHook", "PoolFeesRescued", "PoolFeesRescued(bytes32,address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2FeeEscrow","event":"Claimed"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2FeeEscrow", "Claimed", "Claimed(address,uint256)"));
});

indexer.onEvent({"contract":"PonsV2FeeEscrow","event":"ClaimedToken"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2FeeEscrow", "ClaimedToken", "ClaimedToken(address,address,uint256)"));
});

indexer.onEvent({"contract":"PonsV2FeeEscrow","event":"Credited"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2FeeEscrow", "Credited", "Credited(address,address,uint256)"));
});

indexer.onEvent({"contract":"PonsV2FeeEscrow","event":"CreditedToken"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2FeeEscrow", "CreditedToken", "CreditedToken(address,address,address,uint256)"));
});

indexer.onEvent({"contract":"PonsV2BuybackVault","event":"Locked"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2BuybackVault", "Locked", "Locked(address,address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2BuybackVault","event":"Released"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2BuybackVault", "Released", "Released(address,uint256,uint256)"));
});

indexer.onEvent({"contract":"PonsV2BuybackVault","event":"CreatorRecipientUpdated"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2BuybackVault", "CreatorRecipientUpdated", "CreatorRecipientUpdated(address,address,address)"));
});

indexer.onEvent({"contract":"PonsLaunchToken","event":"Transfer"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsLaunchToken", "Transfer", "Transfer(address,address,uint256)"));
    {
      if (event.params.from.toLowerCase() === "0x0000000000000000000000000000000000000000") {
      const id = chainKey(event.chainId, event.srcAddress.toLowerCase());
      const existing = await context.PonsLaunch.get(id);
      if (existing?.canonicalSupply != null && existing.canonicalSupply !== event.params.value) {
        throw new Error("Conflicting PonsLaunch.canonicalSupply evidence for " + id);
      }
      context.PonsLaunch.set({
        id,
        token: event.srcAddress.toLowerCase(),
        curve: existing?.curve,
        deployer: existing?.deployer,
        pairToken: existing?.pairToken,
        launchConfigId: existing?.launchConfigId,
        graduationThreshold: existing?.graduationThreshold,
        canonicalSupply: event.params.value,
        createdBlock: existing?.createdBlock,
        supplyMintBlock: BigInt(event.block.number),
      });
      }
    }
});

indexer.onEvent({"contract":"PonsV2Forwarder","event":"Launched"}, async ({ event, context }) => {
    context.PonsProtocolEvent.set(normalizedEvent(event, "PonsV2Forwarder", "Launched", "Launched(address,address,address,address,uint256,uint256)"));
});

indexer.onEvent({ contract: "UniswapV4PoolManager", event: "Swap", where: () => false }, async ({ event, context }) => {
    if (!await context.PonsPool.get(chainKey(event.chainId, event.params.id))) return;
    context.PonsProtocolEvent.set(normalizedEvent(event, "UniswapV4PoolManager", "Swap", "Swap(bytes32,address,int128,int128,uint160,uint128,int24,uint24)"));
});
